### PR TITLE
Properly return a 1 when a threshold is not met

### LINKED ISSUE #3298: validate threshold does not properly exit with return code 1 when the threshold is not met
`saf validate threshold` should have an exit code of 1 when a threshold is not met. Right now it prints the error message we would expect to stderr but it doesn't set the return code correctly.

Ex:
```bash
wdower@MM299482-PC ~ % cat threshold.fail.yml
---
error.total.min: 1
wdower@MM299482-PC ~ % cat threshold.pass.yml
---
error.total.max: 0
wdower@MM299482-PC ~ % saf validate threshold --input trufflehog-ohdf.json --templateFile threshold.pass.yml
All validation tests passed
wdower@MM299482-PC ~ % echo $?
0
wdower@MM299482-PC ~ % saf validate threshold --input trufflehog-ohdf.json --templateFile threshold.fail.yml
    Error: error.total.min: Threshold not met. Number of received total error controls (0) is less than your set threshold for the number of error controls (1)
wdower@MM299482-PC ~ % echo $?
0
wdower@MM299482-PC ~ %
```
We'd expect the output of that last `saf validate threshold` run to be 1, since the OHDF file didn't pass the threshold (which saf cli correctly indicated in stderr was a fail!).

### PR DESCRIPTION
**Pull request by wdower**
SAF CLI should exit with code 1 when a threshold is not met to enable other automation to properly handle its output without having to parse stderr.

Resolves #3298

### CODE REVIEW

File: src/utils/oclif/baseCommand.ts [hunk 1]
```diff
@@ -61,7 +61,8 @@ export abstract class BaseCommand<T extends typeof Command> extends Command {
     if (err.message.includes('See more help with --help')) {
       this.warn(err.message.replace('--help', `\x1B[93m${process.argv.at(-2)} ${process.argv.at(-1)} -h or --help\x1B[0m`))
     } else {
-      this.warn(err)
+      console.error(err.message)
+      process.exit(1)
```
Comment (wdower) [inline src/utils/oclif/baseCommand.ts:65]: We tried using `this.exit` instead of `process` but it dumped the entire stack trace. What we want is a simple error message to stderr and the return code set correctly. Working within `oclif` doesn't seem to want to allow this.

**Review by georgedias — APPROVED** [review]
Until we hear from `oclif` I support using this work-around

**Review by em-c-rod — APPROVED** [review]
